### ISSUE TITLE
Heroku 

### ISSUE THREAD

**Issue by kamil25963** [Samograje/tasks#10]
Sprawdzić czy da się postawić backend z node.js i mongo db na heroku

**Comment by bartlomiej-szlachta** [comment]
Mongodb jest już utworzone na oficjalnej stronie mongodb, baza działa 😉  Trzeba będzie za to postawić samą aplikację backendową

**Comment by kamil25963** [comment]
Instrukcja aktualizacji backendu, podmienią się wszystkie pliki na serwerze (pewnie się da jakoś podpiąć chumre pod repo, ale taka brutalna wersja myślę, że wystarczy):
1) skopiować katalog z backendem do innej lokalizacji
2) git init
3) heroku login (wcześniej najlepiej się zalogować na stronie)
4) git remote add heroku  [ścieżka do repo]
5) git add .
6) git commit -m "wiadomość"
7) git push heroku master -ff

Jak zobaczycie coś takiego to znaczy, że się udało.
![image](https://user-images.githubusercontent.com/33577175/77828367-455d0080-711b-11ea-889f-2d91d4dc26f5.png)

**Comment by bartlomiej-szlachta** [comment]
Może spróbujmy od razu zrobić tak, żeby każda zmiana kodu na masterze powodowała aktualizaję 😎 kiedyś proponowałeś coś takiego w cgk, a teraz możemy to zrobić tutaj. W razie czego śmiało 😎

**Comment by bartlomiej-szlachta** [comment]
Ale super, że nam już ta apka działa 😀

**Comment by kamil25963** [comment]
Nie wiem czy się tak będzie dało zrobić żeby na heroku przesyłała się tylko zawartość folderu backend :/

**Comment by bartlomiej-szlachta** [comment]
Ok, to zobaczymy później. A jaki jest url do tej aplikacji?
