### ISSUE TITLE
Endpoint usuwający zadanie

### ISSUE THREAD

**Issue by oliwiabrozek** [Samograje/tasks#16]
Analogicznie jak endpointy w #12

**Comment by bartlomiej-szlachta** [comment]
Zakomentowany kod w ciele metody endpointu to kod usuwający zadanie, gdyby zadania nie miały rodzica w postaci urządzenia. Obecnie trzeba będzie to zadanie rozwiązać inaczej - najpierw wyszukać urządzenie po `deviceId`, dostać się do jego zadań, znaleźć wybrane zadanie, usunąć je z listy i zapisać całe urządzenie.
