### ISSUE TITLE
Scena ustawień

### ISSUE THREAD

**Issue by kamil-rusin** [Samograje/tasks#25]
Scena ta powinna zawierać:
- switch'a dla zmieniania motywu (dodane w późniejszym czasie).
- opcje na sortowanie. Może być w formie radio buttonów lub wybierane z listy (implementacja później).

![image](https://user-images.githubusercontent.com/48494453/78424383-6cf91f00-766d-11ea-9ae0-971bab4a7066.png)

**Comment by bartlomiej-szlachta** [comment]
@kamil-rusin Jak myślisz, czy warto wykorzystać [`SectionList`](https://reactnative.dev/docs/sectionlist)? Podział na sekcje aż się prosi o `SectionList`, za to u nas za każdym razem mamy inny `Item`. Ewentualnie mogę to zrobić po prostu na widokach, wykorzystując `View`

**Comment by kamil-rusin** [comment]
> @kamil-rusin Jak myślisz, czy warto wykorzystać [`SectionList`](https://reactnative.dev/docs/sectionlist)? Podział na sekcje aż się prosi o `SectionList`, za to u nas za każdym razem mamy inny `Item`. Ewentualnie mogę to zrobić po prostu na widokach, wykorzystując `View`

To SectionList nawet bardziej pasuje nam do głównej sceny z listą tasków. Nie trzeba będzie używać dwóch FlatList. Dodatkowo to ma pullToRefresh co bardzo by się przydało na głównej scenie.

Myślę, że fajna opcja do przetestowania w scenie ustawień. Łatwo będzie można dodać kolejne pole do edycji stylu na przykład. Śmiało możesz próbować 😄
