### ISSUE TITLE
Dodanie motywów Domyślny/Ciemny

### ISSUE THREAD

**Issue by kamil-rusin** [Samograje/tasks#26]
Przykładowa implementacja motywu w projekcie:
`import { Provider as PaperProvider } from 'react-native-paper';`
`import { MainTheme } from './src/constants/MainTheme';`

`<PaperProvider theme={MainTheme}>`
`            <App />`
`</PaperProvider>`

Ponadto należy zaimplementować zmianę motywu w scenie z ustawieniami.

**Comment by bartlomiej-szlachta** [comment]
Nie działa mi to z tym `react-native-paper` 😞 robię tak:
```
...

import { DefaultTheme, Provider as PaperProvider } from 'react-native-paper';

...

const App = () => (
  <PaperProvider theme={{
    ...DefaultTheme,
    dark: true,
  }}>
    <NavigationContainer>

...
```

a nie ma żadnej różnicy. Dokumentacja też taka trochę uboga. Mógłbyś pomóc to ogarnać @kamil-rusin?

**Comment by bartlomiej-szlachta** [comment]
Kamil R:
> musimy componenty pod to dostosować, żeby to korzystało z kolorów używanych w naszym motywie
> `<PaperProvider theme={DarkTheme}>`
> możesz tak na górze tego użyć
> DarkTheme z `react-native-paper`
> to zobaczysz, że zmienią się te kolory których mi nie zmienialiśmy
> u mnie się zmienia na ekranie o dziwo xD
> te elementy z react-native-paper same się aktualizują jbc
> ale i tak trzeba pododawać używanie kolorków z motywu
> [tu masz jakie ustawienia ma domyślny motyw](https://github.com/callstack/react-native-paper/blob/master/src/styles/DefaultTheme.tsx?fbclid=IwAR1wkNDg1aQs2nStKFrJ7pkxsqXdRIgK9KfzwJO40cM3JE0YC9p7lP0p6bg)
> 
![image](https://user-images.githubusercontent.com/37980016/79861348-9091c880-83d4-11ea-8817-13efb0bdd249.png)
> tutaj tak możesz dla testów sprawdzić czy działa
> ale u mnie działało od razu na twojej gałęzi więc luzik

**Comment by oliwiabrozek** [comment]
https://reactnavigation.org/docs/themes/
