### ISSUE TITLE
Launch screen

### ISSUE THREAD

**Issue by oliwiabrozek** [Samograje/tasks#42]

**Comment by bartlomiej-szlachta** [comment]
Możliwe, że użycie expo w #56 już nam ten splash screen dodało, trzeba sprawdzić 😎

**Comment by bartlomiej-szlachta** [comment]
Bo jest tam plik `assets/splash.png` i rzeczywiście wyświetla się on przy ładowaniu apki w expo

**Comment by oliwiabrozek** [comment]
Domyślnie jest po prostu biały ekran, ale Expo bardzo ułatwia dostosowanie launch screena. Jesli nie mielibyśmy Expo, nie zrobilibyśmy tego dla IOSa.
