### ISSUE TITLE
FAB nie jest dostępny podczas ładowania listy tasków

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/tasks#45]
Chyba spoko by było, gdyby był dostępny już na początku

**Comment by kamil25963** [comment]
Specjalnie nie jest dostępny. Mi się wydaje, że go nie powinno być. Nie ma danych = nie ma połączenia z bazą, a skoro go nie ma to możliwość użycia przycisku jest zbędna.

**Comment by bartlomiej-szlachta** [comment]
Jak dla mnie sensowne wydaje się włączenie tego przycisku już przy ładowaniu, ale to uzgodnijmy wszyscy razem, jak ma być

**Comment by kamil25963** [comment]
Proponuje ustawić widoczność tylko jeśli dane się załadują poprawnie, jeśli nie to go nie będzie widać.
