### ISSUE TITLE
Użycie expo

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/tasks#46]
Ponoć można przetestować aplikację na iOS przy wykorzystaniu expo i nie trzeba mieć maca! 😮 wystarczy zainstalować apkę na iOS. Mój tata ma iPhone'a, więc mogę przetestować, no ale apka musi używać expo.

Najlepiej by było:
1. usunąć wszystkie pliki oprócz katalogu `src` i pliku `README.md`
2. utworzyć nowy projekt przy użyciu templatki od expo
3. przekopiować te pliki do naszego projektu
4. uzupełnić dependencies w `package.json

`package.json` powinien zawierać skrypt `eject`, który pozwala na zrezygnowanie z expo i dodanie plików natywnych.

W ogóle przy okazji pozbylibyśmy się problematycznego `unimodules` 😉

**Comment by kamil25963** [comment]
https://stackoverflow.com/questions/56694295/appregistry-registercomponent-not-working-with-expo

czy to nie będzie problemem? robie właśnie nawigacje w kontaktach i natknąłem się na taki problem
