### ISSUE TITLE
Warning na liście tasków

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/tasks#47]
![Screenshot_20200418-231256](https://user-images.githubusercontent.com/37980016/79671397-43420b00-81ca-11ea-8bb8-142c4b854705.png)

**Comment by kamil25963** [comment]
Wiem, nie wiem jak go usunąć w taki sposób żeby to działało tak jak teraz Problem polega na tym, że FlatList jest w ScrollView

**Comment by bartlomiej-szlachta** [comment]
Spróbuj w ogóle wywalić `ScrollView`, może nie jest tam w ogóle potrzebne

**Comment by kamil-rusin** [comment]
Można spróbować zrobić ListSection tak jak w #25.  Chociaż w pracy też mamy taki warning i nikt się tym nie przejmuje xD

**Comment by bartlomiej-szlachta** [comment]
Haha spoko, to jak co to zamknijcie issue :stuck_out_tongue_winking_eye:
