### ISSUE TITLE
Projekt interfejsu użytkownika

### ISSUE THREAD

**Issue by oliwiabrozek** [Samograje/tasks#5]

**Comment by kamil-rusin** [comment]
![image](https://i.imgur.com/lMlUBRY.png)
Przykładowa moja koncepcja:

1. Ekran główny
- Taski we FlatLiście -> renderujemy tylko tytuł taska + badge (nic nie trzeba kodować)  z kolorem, który określa ważność taska, 
- Przycisk (+) w prawym dolnym rogu, gotowe z Material Designu z biblioteki
- Checkbox z lewej, który pozwoli zaznaczyć ptaszkiem czy danego taska zrobiliśmy -> jeżeli jakiekolwiek jest zaznaczone to dynamicznie (do dogadania w którym miejscu) przycisk do zapisania tasków jako zrobione lub bottom navigation buttons, (też już gotowa implementacja) z przyciskami, np. usuń, zrobione, archiwizuj
?, 
- sortowanie tasków na górze od najbliższych do zrobienia
- zamiast tego 'dzisiaj', 'jutro' można dać taski według kategorii, np. 'do zrobienia', 'zrobione', 'na kiedyś' XD
- Hamburger Menu do przejścia w ekran ustawień, lub tak jak wspomniałem bottom navigation i przejście do ustawień

2. Ekran dodania taska:
- zależy jakie pola chcemy, ale jedno na tytul, drugie multiline input na treść
- prawy dolny róg button z ptaszkiem -> zapisz taska

3. Ekran ustawień
- wybór motywu
- może wybór sortowania po czym, np. tytuł, data zrobienia (najnowsze/od najstarszych),
- co tam ustalimy innego

**Comment by bartlomiej-szlachta** [comment]
@kamil-rusin Ta koncepcja wydaje się być bardzo rozbudowana, jeśli ma być i hamburger i bottom navigation. Poza tym hamburger jest niewygodny, szczególnie jeśli ma tam się znajdować tylko jedna pozycja.

Myślę, że można by zacząć od czegoś tak prostego, jak tylko możliwe, np:


![IMG_20200325_193911](https://user-images.githubusercontent.com/37980016/77573341-ceccc280-6ed0-11ea-91eb-09770d1156e5.jpg)
![IMG_20200325_193913](https://user-images.githubusercontent.com/37980016/77573391-e60bb000-6ed0-11ea-92a6-2afa0df33593.jpg)
![IMG_20200325_193916](https://user-images.githubusercontent.com/37980016/77573709-5d414400-6ed1-11ea-966d-402440d88728.jpg)

W powyższym przykładzie do ustawień przechodzi się bezpośrednio z listy przez ikonę na Topbarze, nie ma żadnego hamburgera ani bottom navigation, wydaje mi się to dużo prostsze.

Co do floating button (tego w dolnym prawym rogu), można go umiejscowić na Topbarze, bo na iOS nie ma żadnych takich przycisków. Nie jestem pewien, jak RN ogarnie ten przycisk na iOS, ale wydaje mi się, że nie będzie to takie super proste.

Pomysł z checkboxami na elementach listy może stwarzać ryzyko przypadkowych naciśnień przy użytkowaniu, ale wydaje się być spoko pomysłem ogólnie. Możemy np najpierw zrobić bez niego, a dopiero później dodać go na elementy listy.

**Comment by kamil25963** [comment]
Ostateczna wersja:
![projekt](https://user-images.githubusercontent.com/33577175/77684553-6f3ae980-6f9a-11ea-9f95-14eeb0fd9150.png)
