### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by oliwiabrozek** [Samograje/tasks#80]
W celu zaliczenia efektu 4 („zna metody testowania aplikacji z uwzględnieniem specyfiki urządzeń mobilnych i ich wyposażenia, potrafi udokumentować projekt w celu umożliwienia testów innym programistom”) należy przygotować dokumentację zawierającą:

a. opis systematycznych testów automatycznych i/lub manualnych (dotyczy to zarówno testów jednostkowych poszczególnych modułów kodu, jak i testów UX). Z dokumentacji powinno wynikać rozwiązanie co najmniej jednego problemu zidentyfikowanego w trakcie testowania
b. schemat struktury wewnętrznej aplikacji: projekt wykorzystanych klas/struktur danych, pozwalający zrozumieć, interpretować i modyfikować działanie aplikacji.
c. zrzut tablicy Trello/innego narzędzia wspomagającego zarządzanie projektem.

Całość dokumentacji może mieć formę prezentacji lub dokumentu pdf.

**Sugerowany termin przesłania tej części dokumentacji: 29.05.2020.**

**Comment by kamil-rusin** [comment]
@kamil25963 @bartlomiej-szlachta prosimy o recenzję dokumentacji i zgłoszenie poprawek 😄

**Comment by kamil-rusin** [comment]
Finito - proszę przejrzeć 😄

**Comment by bartlomiej-szlachta** [comment]
Jak dla mnie spoko 😎

**Comment by kamil25963** [comment]
spoko
