### ISSUE TITLE
Film multimedialny przedstawiający działającą aplikację

### ISSUE THREAD

**Issue by oliwiabrozek** [Samograje/tasks#81]
W celu zaliczenia efektu 3 („potrafi dobrać i obsługiwać języki programowania oraz środowiska programistyczne do tworzenia aplikacji dla systemu iOS”) należy przygotować film multimedialny przedstawiający działającą aplikację, ilustrujący w szczególności spełnienie wymagań 1-5 a także udostępnić repozytorium plików źródłowych projektu i wgrać archiwum z kodem źródłowym na udostępniony zasób sieciowy (repozytorium i archiwum powinny zawierać dokładnie tą samą wersję aplikacji!). Nagrywana aplikacja może być uruchomiona w środowisku emulatora, symulatora, przeglądarki internetowej, urządzenia mobilnego innego niż iOS, urządzenia mobilnego z iOS – w zależności od dostępności sprzętu i specyfiki wybranego narzędzia. 

Wymagania 1-5:
1. możliwość parametryzowania zapytań (np. ustalenie miejscowości dla pogodynki wg wpisu użytkownika i odczytu GPS)
2. nieblokujące się GUI (przetwarzanie długich operacji w wątkach, wskaźnik postępu, odporność na brak połączenia sieciowego)
3. co najmniej 3 widoki/okienka, w tym co najmniej dwa zależne od siebie (np. widok master-detail)
4. dostosowanie do różnych rozmiarów urządzeń (tablety i telefony)
5. odporność na błędy użytkownika (w tym obsługa znaków narodowych), przynajmniej częściowa zgodność ze standardami UX dla iOS (poprawne wyświetlanie list, obsługa dowolnej ilości wyników, właściwe ikony)

**Sugerowany termin przesłania tej części dokumentacji: 8.06.2020.**

**Comment by bartlomiej-szlachta** [comment]
Co do wymagania nr 4: mogę nagrać filmik na tym małym iPhone

**Comment by kamil-rusin** [comment]
@bartlomiej-szlachta czy issue można już zamknąć?

**Comment by bartlomiej-szlachta** [comment]
Tak 😄
