### ISSUE TITLE
Warning na liście tasków

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/tasks#83]
Po załadowaniu rekordów listy pojawia się warning `VirtualizedLists should never be nested inside plain ScrollViews with the  same orientation - use another VirtualizedList-backed container instead`. Nie przeszkadza to w samym działaniu aplikacji, ale przeszkadza przy nagrywaniu filmiku z prezentacją, także warto to rozwiązać. W praktyce można wywalić `ScrollView` na tym ekranie - nie jest potrzebne, bo sama lista się scrolluje w swoim zakresie.

**Comment by kamil25963** [comment]
Jak wyrzucę scroll view to przewijanie tasków nie będzie działać tak jak działa obecnie, spędziłem dużo czasu nad tym problemem i już na jego temat byłą dyskusja. Oliwia w kontaktach zrobiła to tak, że podzieliła ekran na pół i się scrolluje w ramach tej połówki, a mi tu zależało żeby dwie listy dało się skrollować na całym ekranie. Erroe wynika z tego, że dlat lista jest w scroll view (sama flat lista jest tak jakby już scroll view i dlatego). Nie planuje przebudowywać całego widoku aktualnie, warningi zawsze można wyłączyć, w niczym nie przeszkadzają. Nawet @kamil-rusin  pisał, że mają takie w pracy i sie nikt tym nie przejmuje
