### ISSUE TITLE
Jeszcze jeden warning na liście tasków

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/tasks#86]
`Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.`. Nie przeszkadza to w działaniu aplikacji, ale przeszkadza przy nagrywaniu prezentacji

**Comment by kamil25963** [comment]
Ten warning nie zniknie, bo dotyczy starego komponentu do gestów i przesuwania w prawo. Nie znalazłem prostego w implementacji zamiennika ani nie potrafię go 'wyłączyć'
